language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - pip install -r dev_requirements.txt
  - python setup.py install
script:
  - make test
  - make coverage
after_script:
  coveralls --verbose
